// Generated by CoffeeScript 1.4.0
(function() {
  var Animal, animal;

  console.log("Hello CoffeeScript!");

  Animal = (function() {

    function Animal() {}

    Animal.prototype.price = 5;

    Animal.prototype.sell = function() {
      return console.log("Give me " + this.price + " shillings!");
    };

    return Animal;

  })();

  animal = new Animal;

  animal.sell();

}).call(this);
